Updated to mxml 3.3.1

diff --git a/mxml.mod/mxml/Makefile.in b/mxml.mod/mxml/Makefile.in
--- a/mxml.mod/mxml/Makefile.in
+++ b/mxml.mod/mxml/Makefile.in
@@ -3,7 +3,7 @@
 #
 # https://www.msweet.org/mxml
 #
-# Copyright © 2003-2019 by Michael R Sweet.
+# Copyright © 2003-2021 by Michael R Sweet.
 #
 # Licensed under Apache License v2.0.  See the file "LICENSE" for more
 # information.
@@ -17,20 +17,22 @@ AR		=	@AR@
 ARFLAGS		=	@ARFLAGS@
 ARCHFLAGS	=	@ARCHFLAGS@
 CC		=	@CC@
-CFLAGS		=	$(OPTIM) $(ARCHFLAGS) @CFLAGS@ @CPPFLAGS@ @PTHREAD_FLAGS@
+CFLAGS		=	$(OPTIM) $(ARCHFLAGS) @CFLAGS@ $(CPPFLAGS) $(WARNINGS)
 CP		=	@CP@
+CPPFLAGS	=	@CPPFLAGS@
 DSO		=	@DSO@
 DSOFLAGS	=	@DSOFLAGS@
 LDFLAGS		=	$(OPTIM) $(ARCHFLAGS) @LDFLAGS@
 INSTALL		=	@INSTALL@
 LIBMXML		=	@LIBMXML@
-LIBS		=	@LIBS@ @PTHREAD_LIBS@
+LIBS		=	@LIBS@
 LN		=	@LN@ -s
 MKDIR		=	@MKDIR@
 OPTIM		=	@OPTIM@
 RANLIB		=	@RANLIB@
 RM		=	@RM@ -f
 SHELL		=	/bin/sh
+WARNINGS	=	@WARNINGS@
 
 
 #
@@ -52,10 +54,10 @@ BUILDROOT	=	$(DSTROOT)
 # Install commands...
 #
 
-INSTALL_BIN	=	$(LIBTOOL) $(INSTALL) -m 755
+INSTALL_BIN	=	$(INSTALL) -m 755
 INSTALL_DATA	=	$(INSTALL) -m 644
 INSTALL_DIR	=	$(INSTALL) -d
-INSTALL_LIB	=	$(LIBTOOL) $(INSTALL) -m 755
+INSTALL_LIB	=	$(INSTALL) -m 755
 INSTALL_MAN	=	$(INSTALL) -m 644
 INSTALL_SCRIPT	=	$(INSTALL) -m 755
 
@@ -75,7 +77,8 @@ INSTALL_SCRIPT	=	$(INSTALL) -m 755
 # Targets...
 #
 
-DOCFILES	=	doc/mxml.html doc/mxmldoc.xsd README.md COPYING CHANGES.md
+DOCFILES	=	doc/mxml.epub doc/mxml.html doc/mxml-cover.png \
+			CHANGES.md LICENSE NOTICE README.md
 PUBLIBOBJS	=	mxml-attr.o mxml-entity.o mxml-file.o mxml-get.o \
 			mxml-index.o mxml-node.o mxml-search.o mxml-set.o
 LIBOBJS		=	$(PUBLIBOBJS) mxml-private.o mxml-string.o
@@ -100,10 +103,13 @@ clean:
 	echo Cleaning build files...
 	$(RM) $(OBJS) $(ALLTARGETS)
 	$(RM) mxml1.dll
+	$(RM) mxml1.lib
 	$(RM) libmxml.a
+	$(RM) libmxml.so
+	$(RM) libmxml.so.1
 	$(RM) libmxml.so.1.6
-	$(RM) libmxml.sl.1
 	$(RM) libmxml.1.dylib
+	$(RM) libmxml.dylib
 
 
 #
@@ -113,24 +119,13 @@ clean:
 distclean:	clean
 	echo Cleaning distribution files...
 	$(RM) config.cache config.log config.status
-	$(RM) Makefile config.h
+	$(RM) Makefile config.h mxml.pc
+	$(RM) test.xmlfd
+	$(RM) temp1.xml temp1.xmlfd temp1s.xml
+	$(RM) temp2.xml temp2s.xml
 	$(RM) -r autom4te*.cache
 	$(RM) *.bck *.bak
 	$(RM) -r clang
-
-
-#
-# Run the clang.llvm.org static code analysis tool on the C sources.
-#
-
-.PHONY: clang clang-changes
-clang:
-	echo Doing static code analysis of all code using CLANG...
-	$(RM) -r clang
-	scan-build -V -k -o `pwd`/clang $(MAKE) $(MFLAGS) clean all
-clang-changes:
-	echo Doing static code analysis of changed code using CLANG...
-	scan-build -V -k -o `pwd`/clang $(MAKE) $(MFLAGS) all
 
 
 #
@@ -167,6 +162,7 @@ install-libmxml.so.1.6:	libmxml.so.1.6
 	$(LN) libmxml.so.1.6 $(BUILDROOT)$(libdir)/libmxml.so
 	$(RM) $(BUILDROOT)$(libdir)/libmxml.so.1
 	$(LN) libmxml.so.1.6 $(BUILDROOT)$(libdir)/libmxml.so.1
+	$(LDCONFIG)
 
 install-libmxml.1.dylib: libmxml.1.dylib
 	echo Installing libmxml.dylib to $(BUILDROOT)$(libdir)...
@@ -198,12 +194,41 @@ uninstall-libmxml.so.1.6:
 	echo Uninstalling libmxml.so from $(BUILDROOT)$(libdir)...
 	$(RM) $(BUILDROOT)$(libdir)/libmxml.so
 	$(RM) $(BUILDROOT)$(libdir)/libmxml.so.1
-	$(RM) $(BUILDROOT)$(libdir)/libmxml.so.1.4
+	$(RM) $(BUILDROOT)$(libdir)/libmxml.so.1.6
+	$(LDCONFIG)
 
 uninstall-libmxml.1.dylib:
 	echo Uninstalling libmxml.dylib from $(BUILDROOT)$(libdir)...
 	$(RM) $(BUILDROOT)$(libdir)/libmxml.dylib
 	$(RM) $(BUILDROOT)$(libdir)/libmxml.1.dylib
+
+
+#
+# Test everything...
+#
+
+test:	testmxml
+	@echo Testing library...
+	./testmxml test.xml temp1s.xml >temp1.xml
+	./testmxml temp1.xml temp2s.xml >temp2.xml
+	@if cmp temp1.xml temp2.xml; then \
+		echo Stdio file test passed!; \
+		$(RM) temp2.xml temp2s.xml; \
+	else \
+		echo Stdio file test failed!; \
+	fi
+	@if cmp temp1.xml temp1s.xml; then \
+		echo String test passed!; \
+		$(RM) temp1.xml temp1s.xml; \
+	else \
+		echo String test failed!; \
+	fi
+	@if cmp test.xml test.xmlfd; then \
+		echo File descriptor test passed!; \
+		$(RM) test.xmlfd temp1.xmlfd; \
+	else \
+		echo File descriptor test failed!; \
+	fi
 
 
 #
@@ -275,33 +300,33 @@ libmxml.1.dylib:	$(LIBOBJS)
 testmxml:	libmxml.a testmxml.o
 	echo Linking $@...
 	$(CC) $(LDFLAGS) -o $@ testmxml.o libmxml.a $(LIBS)
-	@echo Testing library...
-	./testmxml test.xml temp1s.xml >temp1.xml
-	./testmxml temp1.xml temp2s.xml >temp2.xml
-	@if cmp temp1.xml temp2.xml; then \
-		echo Stdio file test passed!; \
-		$(RM) temp2.xml temp2s.xml; \
-	else \
-		echo Stdio file test failed!; \
-	fi
-	@if cmp temp1.xml temp1s.xml; then \
-		echo String test passed!; \
-		$(RM) temp1.xml temp1s.xml; \
-	else \
-		echo String test failed!; \
-	fi
-	@if cmp test.xml test.xmlfd; then \
-		echo File descriptor test passed!; \
-		$(RM) test.xmlfd; \
-	else \
-		echo File descriptor test failed!; \
-	fi
 
 testmxml-vg:	$(LIBOBJS) testmxml.o
 	echo Linking $@...
 	$(CC) $(LDFLAGS) -o $@ testmxml.o $(LIBOBJS) $(LIBS)
 
 testmxml.o:	mxml.h
+
+
+#
+# Analyze code with the Clang static analyzer <https://clang-analyzer.llvm.org>
+#
+
+.PHONY: clang
+clang:
+	clang $(CPPFLAGS) --analyze $(OBJS:.o=.c) 2>clang.log
+	rm -rf $(OBJS:.o=.plist)
+	test -s clang.log && (echo "$(GHA_ERROR)Clang detected issues."; echo ""; cat clang.log; exit 1) || exit 0
+
+
+#
+# Analyze code using Cppcheck <http://cppcheck.sourceforge.net>
+#
+
+.PHONY: cppcheck
+cppcheck:
+	cppcheck $(CPPFLAGS) --template=gcc --addon=cert.py --suppressions-list=.cppcheck $(OBJS:.o=.c) 2>cppcheck.log
+	test -s cppcheck.log && (echo "$(GHA_ERROR)Cppcheck detected issues."; echo ""; cat cppcheck.log; exit 1) || exit 0
 
 
 #
