Updated to zsv 1.3.0 (#62)

diff --git a/csv.mod/zsv/app/ext_example/configure b/csv.mod/zsv/app/ext_example/configure
--- a/csv.mod/zsv/app/ext_example/configure
+++ b/csv.mod/zsv/app/ext_example/configure
@@ -25,6 +25,7 @@ Fine tuning of the installation directories:
 
 Optional features:
   --try-avx512            use avx512 instructions, if available (not recommended)
+  --enable-sheet          compile with 'sheet' feature (requires ncurses) [yes]
   --enable-small-lut      build with smaller lookup tables [no]
   --enable-debug-stderr   build with debug msgs in stderr [no]
   --enable-pie            build with position independent executables [auto]
@@ -264,6 +265,7 @@ DOCDIR='$(PREFIX)/share/doc'
 MANDIR='$(PREFIX)/share/man'
 
 MINIMAL=no
+TRY_SHEET=auto
 
 help=yes
 usesmalllut=no
@@ -301,6 +303,11 @@ for arg ; do
         --disable-jq|--enable-jq=no) usejq=no ;;
         --enable-pic=auto) usepic=auto ;;
         --disable-pic|--enable-pic=no) usepic=no ;;
+
+        --enable-sheet|--enable-sheet=yes) TRY_SHEET=yes;;
+        --enable-sheet=auto) TRY_SHEET=auto;;
+        --disable-sheet|--enable-sheet=no) TRY_SHEET=no;;
+        
         --enable-*|--disable-*|--with-*|--without-*|--*dir=*|--build=*) ;;
         -* ) echo "$0: unknown option $arg" ;;
         CC=*) CC=${arg#*=} ;;
@@ -450,6 +457,36 @@ tryflag CFLAGS_VECTORIZE_MISSED -fopt-info-vec-missed
 tryflag CFLAGS_VECTORIZE_ALL -fopt-info-vec-all
 tryflag CFLAGS_OPENMP -fopenmp
 
+if [ "$TRY_SHEET" != "no" ]; then
+    if tryldflag LDFLAGS_NCURSESW -lncursesw -L"$PREFIX"/lib ; then
+        LDFLAGS_NCURSES=-lncursesw
+        NCLIB=ncursesw
+        if [ "$NCURSES_DYNAMIC" = "" ] ; then
+            CFLAGS_NCURSES="-DHAVE_NCURSESW -DNCURSES_STATIC"
+        else
+            CFLAGS_NCURSES="-DHAVE_NCURSESW"
+        fi
+    fi
+    if tryldflag LDFLAGS_NCURSES -lncurses -L"$PREFIX"/lib ; then
+        NCLIB=ncurses
+        if [ "$NCURSES_DYNAMIC" = "" ] ; then
+            CFLAGS_NCURSES="$CFLAGS_NCURSES -DHAVE_NCURSES -DNCURSES_STATIC"
+        else
+            CFLAGS_NCURSES="$CFLAGS_NCURSES -DHAVE_NCURSES"
+        fi
+    fi
+    ZSVSHEET_BUILD=1
+
+    if [ "$TRY_SHEET" = "yes" ] ; then
+        echo "Error: could not find either ncurses or ncursesw library; cannot build 'sheet' feature"
+        exit 1
+    fi
+    if [ "$LDFLAGS_NCURSES" = "" ] ; then
+        echo "Warning: could not find either ncurses or ncursesw library; cannot build 'sheet' feature"
+        ZSVSHEET_BUILD=0
+    fi
+fi
+
 if test "$usepie" = "yes" ; then
     tryflag CFLAGS_PIE -fpie || tryflag CFLAGS_PIE -fPIE
 fi
@@ -541,10 +578,12 @@ if [ "$usejq" = "yes" ] || [ "$usejq" = "auto" ] ; then
             echo "Error: --enable-jq specified, but not found"
             exit 1
         fi
-    if ! [ "$LDFLAGS_JQ" = "" ] ; then
+    if [ "$LDFLAGS_JQ" != "" ] ; then
         tryldflag LDFLAGS_JQ -lm
         tryldflag LDFLAGS_JQ -lshlwapi
-        tryldflag LDFLAGS_JQ -pthread
+        if [ "$NO_THREADING" != "1" ]; then
+            tryldflag LDFLAGS_JQ -pthread
+        fi
     fi
 fi
 
@@ -629,6 +668,8 @@ CFLAGS_VECTORIZE_ALL = $CFLAGS_VECTORIZE_ALL
 CFLAGS_OPENMP = $CFLAGS_OPENMP
 
 ZSV_EXTRAS = $ZSV_EXTRAS
+
+ZSVSHEET_BUILD = $ZSVSHEET_BUILD
 
 $NO_HAVE
 $USE_LIBS
diff --git a/csv.mod/zsv/configure b/csv.mod/zsv/configure
--- a/csv.mod/zsv/configure
+++ b/csv.mod/zsv/configure
@@ -18,6 +18,12 @@ Optional configuration:
   --arch=ARCH             use -march=ARCH. Set to 'none' for none, else defaults to 'native'
   --jq-prefix=JQ_PREFIX   specify directory containing lib/libjq and include/jq.h
                           defaults to PREFIX if not specified and PREFIX/include/jq.h exists
+  --pcre2-8-prefix=PCRE2_8_PREFIX
+                          no=do not use pcre2
+                          builtin=build from included source (pcre2-10.47)
+                          otherwise, specify dir with lib/libpcre2-8 and include/pcre2-8.h
+                          defaults to 'builtin' if not specified
+  --no-parallel           disable parallelization in the CLI 'select' command
 
 Installation directories:
   --prefix=PREFIX         main installation prefix [\$PREFIX or /usr/local]
@@ -34,12 +40,16 @@ Optional features:
   --force-avx             force compile with (no CPU check) or without -mavx [auto]
   --force-sse2            force compile with (no CPU check) or without -msse2 [auto]
   --enable-sheet          compile with 'sheet' feature (requires ncurses) [yes]
-  --ncurses-dynamic       compile without NCURSES_STATIC or NCURSESW_STATIC defines
+  --enable-shared         build/install zsv shared library
+  --ncurses-dynamic       compile without NCURSES_STATIC
   --enable-lto            compile with LTO (works with some but not all platforms/compilers) [no]
   --enable-whole-program  compile without -fwhole-program even if no -flto [yes]
   --enable-pie            build with position independent executables [auto]
   --enable-pic            build with position independent shared libraries [auto]
   --enable-termcap        build with ncurses / termcap (used by \`pretty\` to get console width) [auto]
+  --disable-stdin         disable stdin from CLI commands
+  --enable-simdutf        use simdutf for 'check --utf8'. Faster, but adds ~300k to binary
+  --disable-only-crlf     disable the --only-crlf parsing option
 
 Some influential environment variables:
   CC                      C compiler command [detected]
@@ -51,6 +61,7 @@ Some influential environment variables:
   LDFLAGS                 Linker flags
 
   CROSS_COMPILING=no      Set to yes to disable auto-detect compilation flags
+  NO_THREADING            Set to 1 to disable threading
 
 Use these variables to override the choices made by configure.
 
@@ -68,6 +79,7 @@ EOF
 }
 echo () { printf "%s\n" "$*" ; }
 fail () { echo "$*" ; exit 1 ; }
+# shellcheck disable=SC2329
 fnmatch () { eval "case \"\$2\" in $1) return 0 ;; *) return 1 ;; esac" ; }
 cmdexists () { type "$1" >/dev/null 2>&1 ; }
 trycc1 () { test -z "$CC" && cmdexists "$1" && ( "$1" --version | grep -i gcc ) >/dev/null 2>/dev/null && CC=$1 ; }
@@ -77,7 +89,7 @@ tryranlib () { test -z "$RANLIB" && cmdexists "$1" && RANLIB=$1 ; }
 tryawk () { test -z "$AWK" && "$1" 'function works () {return 0} BEGIN{exit works()}' && AWK=$1 ; }
 trymake() {
     if test -z "$MAKE" && cmdexists "$1" ; then
-    v=$($1 --version | grep 'GNU Make' | sed -e 's/.*Make //')
+        v=$($1 --version | grep 'GNU Make' | sed -e 's/.*Make //')
         if [ "$v" = "" ] ; then
             printf "Found but not using non-GNU make (%s)..." "$1"
         else
@@ -85,7 +97,7 @@ trymake() {
             maj=$(echo "$v" | cut -d. -f 1)
             min=$(echo "$v" | cut -d. -f 2)
             if ! test "$maj" -gt 3 -o '(' "$maj" -eq 3 -a "$min" -ge 81 ')'; then
-                printf "Warning: using make, but version %s < 3.81 has not been tested. " "$v"
+                printf "WARNING: using make, but version %s < 3.81 has not been tested. " "$v"
             fi
         fi
     fi
@@ -100,14 +112,14 @@ trycchdr () {
     printf "checking whether there is a header called %s... " "$2"
     dn=$(dirname "$2")
     if [ "$dn" != "" ]; then
-    dn="/$dn"
-    bn=$(basename "$2")
-    for x in $CCSEARCHPATH ; do
-        fnd=$fnd"$x$dn "
-    done
+        dn="/$dn"
+        bn=$(basename "$2")
+        for x in $CCSEARCHPATH ; do
+            fnd=$fnd"$x$dn "
+        done
     else
-    bn="$2"
-    fnd=$CCSEARCHPATH
+        bn="$2"
+        fnd=$CCSEARCHPATH
     fi
     upper2=$(echo "$2" | tr '[:lower:]' '[:upper:]' | tr . _ | tr / _)
     if find "$fnd" -name "$bn" 2>/dev/null | grep "/$2$" >/dev/null 2>&1 ; then
@@ -178,7 +190,7 @@ NO_$flag = 1"
             echo "Failed: $CC -o $tmpo tmp.c"
             cat "$tmpc"
             echo "------"
-        }>> "$CONFIGFILE".log
+        } >>"$CONFIGFILE".log
         return 1
     fi
 }
@@ -312,16 +324,20 @@ MANDIR="$PREFIX/share/man"
 MINIMAL=no
 
 TRY_SHEET=auto
+BUILD_SHAREDLIB=0
 TRY_LTO=no
 TRY_WHOLE_PROGRAM=auto
 FORCE_AVX2=auto
 FORCE_AVX=auto
 FORCE_SSE2=auto
 
+NO_STDIN=
+
 usepie=auto
 usepic=auto
 usetermcap=auto
 
+ZSV_NO_PARALLEL=
 NCURSES_DYNAMIC=
 for arg ; do
     case "$arg" in
@@ -337,12 +353,19 @@ for arg ; do
         --jq-prefix=*) JQ_PREFIX=${arg#*=} ;;
         JQ_PREFIX=*) JQ_PREFIX=${arg#*=} ;;
 
+        --pcre2-8-prefix=*) PCRE2_8_PREFIX=${arg#*=} ;;
+        PCRE2_8_PREFIX=*) PCRE2_8_PREFIX=${arg#*=} ;;
+
         --prefix=*) ;; # already handled
         --exec-prefix=*) ;; # already handled EXEC_PREFIX=${arg#*=} ;;
         --docdir=*) DOCDIR=${arg#*=} ;;
         --mandir=*) MANDIR=${arg#*=} ;;
         --minimal|--minimal=yes) MINIMAL=yes;;
+
+        --no-parallel) ZSV_NO_PARALLEL=1;;
+
         --try-avx512|--try-avx512=yes) TRY_AVX512=yes;;
+        --try-avx512=no) TRY_AVX512=no;;
 
         --force-avx2|--force-avx2=yes) FORCE_AVX2=yes;;
         --force-avx2=no) FORCE_AVX2=no;;
@@ -359,6 +382,17 @@ for arg ; do
         --enable-sheet=auto) TRY_SHEET=auto;;
         --disable-sheet|--enable-sheet=no) TRY_SHEET=no;;
 
+        --enable-simdutf|--enable-simdutf=yes) USE_SIMDUTF=1;;
+        --enable-simdutf=auto) USE_SIMDUTF=0;;
+        --disable-simdutf|--enable-simdutf=no) USE_SIMDUTF=0;;
+
+        --enable-only-crlf|--enable-only-crlf=yes) ZSV_NO_ONLY_CRLF=0;;
+        --enable-only-crlf=auto) ZSV_NO_ONLY_CRLF=0;;
+        --disable-only-crlf|--enable-only-crlf=no) ZSV_NO_ONLY_CRLF=1;;
+
+        --enable-shared|--enable-shared=yes) BUILD_SHAREDLIB=1;;
+        --disable-shared|--enable-shared=no) BUILD_SHAREDLIB=0;;
+
         --enable-lto|--enable-lto=yes) TRY_LTO=yes;;
         --enable-lto=auto) TRY_LTO=auto;;
         --disable-lto|--enable-lto=no) TRY_LTO=no;;
@@ -374,6 +408,8 @@ for arg ; do
         --enable-termcap|--enable-termcap=yes) usetermcap=yes ;;
         --enable-termcap=auto) usetermcap=auto ;;
         --disable-termcap|--enable-termcap=no) usetermcap=no ;;
+
+        --disable-stdin|--enable-stdin=no) NO_STDIN=1 ;;
 
         --enable-pic=auto) usepic=auto ;;
         --disable-pic|--enable-pic=no) usepic=no ;;
@@ -559,7 +595,7 @@ if [ "$TRY_SHEET" != "no" ]; then
         exit 1
     fi
     if [ "$LDFLAGS_NCURSES" = "" ] ; then
-        echo "Warning: could not find either ncurses or ncursesw library; cannot build 'sheet' feature"
+        echo "WARNING: could not find either ncurses or ncursesw library; cannot build 'sheet' feature"
         ZSVSHEET_BUILD=0
     fi
 fi
@@ -595,19 +631,18 @@ if [ "$FORCE_AVX2" = "no" ]; then
 elif [ "$FORCE_AVX2" = "yes" ] ; then
     CFLAGS_AVX=-mavx2
     if [ "$CROSS_COMPILING" = "no" ] ; then
-        trycpusupport avx2 || echo "warning: avx2 forced but not supported on native CPU"
+        trycpusupport avx2 || echo "WARNING: avx2 forced but not supported on native CPU"
     fi
 elif [ "$FORCE_AVX2" = "auto" ] && [ "$CROSS_COMPILING" = "no" ] ; then
     trycpusupport avx2 && CFLAGS_AVX=-mavx2
 fi
 
-if [ "$FORCE_AVX" = "yes" ] ; then
-    CFLAGS_AVX=-mavx || echo "warning: avx forced but not supported on native CPU"
-elif [ "$FORCE_AVX" = "auto" ] && [ "$CFLAGS_AVX" = "" ] && [ "$CROSS_COMPILING" = "no" ] ; then
-    trycpusupport avx && CFLAGS_AVX=-mavx
-fi
 if [ "$FORCE_AVX" = "no" ]; then
     tryflag CFLAGS -mno-avx
+elif [ "$FORCE_AVX" = "yes" ] ; then
+    CFLAGS_AVX=-mavx || echo "WARNING: avx forced but not supported on native CPU"
+elif [ "$FORCE_AVX" = "auto" ] && [ "$CFLAGS_AVX" = "" ] && [ "$CROSS_COMPILING" = "no" ] ; then
+    trycpusupport avx && CFLAGS_AVX=-mavx
 fi
 
 if [ "$FORCE_SSE2" = "no" ]; then
@@ -618,7 +653,7 @@ elif [ "$FORCE_SSE2" = "yes" ] ; then
         CFLAGS_SSE="$CFLAGS_SSE -msimd128 -experimental-wasm-simd"
     fi
     if [ "$CROSS_COMPILING" = "no" ] ; then
-        trycpusupport sse2 || echo "warning: sse2 forced but not supported on native CPU"
+        trycpusupport sse2 || echo "WARNING: sse2 forced but not supported on native CPU"
     fi
 elif [ "$FORCE_SSE2" = "auto" ] && [ "$CROSS_COMPILING" = "no" ] ; then
     if [ "$CFLAGS_SSE" = "" ] && [ "$CROSS_COMPILING" = "no" ] ; then
@@ -653,7 +688,7 @@ elif [ "$TRY_WHOLE_PROGRAM" = "auto" ] ; then
     fi
 fi
 
-tryflag CFLAGS_OPT -fvisibility=hidden
+tryflag CFLAGS_VISIBILITY_HIDDEN -fvisibility=hidden
 tryldflag LDFLAGS_AUTO -Wl,--gc-sections
 
 if [ "$ARCH" != "none" ] ; then
@@ -684,7 +719,7 @@ fi
 
 # Check function availability
 if [ "$TRY_AVX512" = "yes" ]; then
-    printf "checking whether avx512 instructions are available..."
+    printf "checking whether avx512 instructions are available... "
     HAVE_AVX512=
     tryccfn CFLAGS_AVX_512 "_mm512_movepi8_mask" "immintrin.h" && \
         trycchdr CFLAGS_AVX_512 "immintrin.h" && \
@@ -694,10 +729,10 @@ if [ "$TRY_AVX512" = "yes" ]; then
         CFLAGS_AVX_512="-mbmi -mavx512bw -DHAVE_AVX512=1" && \
         HAVE_AVX512=1
     if [ "$HAVE_AVX512" = "1" ]; then
-    echo "yes"
+        echo "yes"
     else
-    echo "no"
-    echo "WARNING: --try-avx512 option enabled, but no avx512 instruction set available"
+        echo "no"
+        echo "WARNING: --try-avx512 option enabled, but no avx512 instruction set available"
     fi
 fi
 
@@ -719,7 +754,7 @@ if [ "$JQ_PREFIX" = "" ] && [ "$PREFIX" != "" ] && [ -f "$PREFIX/include/jq.h" ]
 fi
 
 if [ "$JQ_PREFIX" != "" ] && [ "$CROSS_COMPILING" = "no" ] ; then
-    echo "checking --prefix-jq ${JQ_PREFIX}"
+    printf '%s' "checking --jq-prefix ${JQ_PREFIX} ... "
     if ! tryldflag LDFLAGS_JQ -ljq -L"$JQ_PREFIX"/lib ; then
         echo "Error: Failed to compile with -ljq and -L$JQ_PREFIX/lib"
         exit 1
@@ -730,10 +765,36 @@ fi
 
 tryldflag LDFLAGS_JQ -lm
 tryldflag LDFLAGS_JQ -lshlwapi
-if [ "$MINGW" = "1" ]; then
-    tryldflag LDFLAGS_TMP -pthread && STATIC_LIBS="$STATIC_LIBS -pthread"
+if [ "$NO_THREADING" != "1" ]; then
+    if [ "$MINGW" = "1" ]; then
+        tryldflag LDFLAGS_TMP -pthread && STATIC_LIBS="$STATIC_LIBS -pthread"
+    else
+        tryldflag LDFLAGS_JQ -pthread
+    fi
+fi
+
+HAVE_PCRE2_8=
+if [ "$PCRE2_8_PREFIX" = "" ] ; then
+    PCRE2_8_PREFIX=builtin
+fi
+if [ "$PCRE2_8_PREFIX" = "builtin" ] ; then
+    HAVE_PCRE2_8=1
 else
-    tryldflag LDFLAGS_JQ -pthread
+    if [ "$PCRE2_8_PREFIX" = "" ] && [ "$PREFIX" != "" ] && [ -f "$PREFIX/include/pcre2.h" ] ; then
+        PCRE2_8_PREFIX="$PREFIX"
+    fi
+
+    if [ "$PCRE2_8_PREFIX" != "no " ] ; then
+        if [ "$PCRE2_8_PREFIX" != "" ] && [ "$CROSS_COMPILING" = "no" ] ; then
+            # TO DO: check for pcre2 static lib
+            printf "%s" "checking --pcre2-8-prefix ${PCRE2_8_PREFIX} ... "
+            if ! tryldflag LDFLAGS_PCRE2_8 -lpcre2-8 -L"$PCRE2_8_PREFIX"/lib ; then
+                echo "Error: Failed to compile with -lpcre2-8 and -L$PCRE2_8_PREFIX/lib"
+            else
+                HAVE_PCRE2_8=1
+            fi
+        fi
+    fi
 fi
 
 tryccfn CFLAGS_AUTO "arc4random_uniform" "stdlib.h" || tryccfn CFLAGS_AUTO "rand_s" "stdlib.h" "" "#define _CRT_RAND_S"
@@ -782,21 +843,25 @@ CFLAGS = $CFLAGS
 LDFLAGS = $LDFLAGS
 CFLAGS_STD = $CFLAGS_STD
 LDFLAGS_STD = $LDFLAGS_STD
-CFLAGS_OPT = $CFLAGS_OPT
+CFLAGS_VISIBILITY_HIDDEN = $CFLAGS_VISIBILITY_HIDDEN
 LDFLAGS_OPT = $LDFLAGS_OPT
 LDFLAGS_TERMCAP = $LDFLAGS_TERMCAP
 JQ_PREFIX = $JQ_PREFIX
 LDFLAGS_JQ = $LDFLAGS_JQ
+
+HAVE_PCRE2_8 = $HAVE_PCRE2_8
+PCRE2_8_PREFIX = $PCRE2_8_PREFIX
+
 STATIC_LIBS = $STATIC_LIBS
 CFLAGS_AUTO = $CFLAGS_AUTO
 CFLAGS_LTO = $CFLAGS_LTO
 LDFLAGS_AUTO = $LDFLAGS_AUTO
 
-HAVE_AVX512=$HAVE_AVX512
+HAVE_AVX512 = $HAVE_AVX512
 
-CFLAGS_AVX_512=$CFLAGS_AVX_512
-CFLAGS_AVX=$CFLAGS_AVX
-CFLAGS_SSE=$CFLAGS_SSE
+CFLAGS_AVX_512 = $CFLAGS_AVX_512
+CFLAGS_AVX = $CFLAGS_AVX
+CFLAGS_SSE = $CFLAGS_SSE
 
 CFLAGS_DEBUG = -U_FORTIFY_SOURCE -UNDEBUG -O0 -g -Wall -Wextra -Wno-missing-field-initializers -Wunused # -g3 -ggdb
 LDFLAGS_DEBUG = -U_FORTIFY_SOURCE -UNDEBUG -O0 -g # -g3 -ggdb
@@ -817,7 +882,17 @@ CFLAGS_NCURSES = $CFLAGS_NCURSES
 
 ZSV_EXTRAS = $ZSV_EXTRAS
 
+BUILD_SHAREDLIB = $BUILD_SHAREDLIB
+
 ZSVSHEET_BUILD = $ZSVSHEET_BUILD
+
+ZSV_NO_PARALLEL = $ZSV_NO_PARALLEL
+
+NO_STDIN = $NO_STDIN
+
+USE_SIMDUTF = $USE_SIMDUTF
+
+ZSV_NO_ONLY_CRLF = $ZSV_NO_ONLY_CRLF
 
 $NO_HAVE
 $USE_LIBS
@@ -828,38 +903,74 @@ exec 1>&3 3>&-
 printf "done\n"
 
 echo ""
-echo "****************************************************************"
-echo "*  zsv configuration                                           *"
-echo "****************************************************************"
+echo "*****************************************************************"
+echo "*  zsv build configuration                                      *"
+echo "*****************************************************************"
 
 if [ "$JQ_PREFIX" != "" ]; then
-    echo "*  - jq-prefix: $JQ_PREFIX                                     *"
+    printf '%-64s*\n' "*  - jq-prefix: $JQ_PREFIX"
+fi
+
+if [ "$PCRE2_8_PREFIX" != "" ] && [ "$HAVE_PCRE2_8" = "1" ]; then
+    printf '%-64s*\n' "*  - pcre2-8-prefix: $PCRE2_8_PREFIX"
+else
+    printf '%-64s*\n' "*  - pcre2-8 -> NOT FOUND"
+    printf '%-64s*\n' "       select and sheet regex features will not be built"
 fi
 
 if [ "$LDFLAGS_TERMCAP" = "" ]; then
-    echo "*  - termcap: no. \`pretty\` will use default width assumption   *"
+    printf '%-64s*\n' "*  - termcap: no. \`pretty\` will use default width assumption"
 else
-    echo "*  - termcap: yes                                              *"
+    printf '%-64s*\n' "*  - termcap: yes"
+fi
+
+if [ "$BUILD_SHAREDLIB" = "1" ]; then
+    printf '%-64s*\n' "*  - build shared library: yes"
+else
+    printf '%-64s*\n' "*  - build shared library: no"
 fi
 
 if [ "$ZSVSHEET_BUILD" = "1" ]; then
-    echo "*  - build sheet feature: yes                                  *"
-    echo "*    ncurses library:     $NCLIB                               *"
+    printf '%-64s*\n' "*  - build sheet feature: yes"
+    if [ "$NCLIB" = "ncurses" ]; then
+        printf '%-64s*\n' "*    ncurses library:     ncurses"
+    elif [ "$NCLIB" = "ncursesw" ]; then
+        printf '%-64s*\n' "*    ncurses library:     ncursesw"
+    fi
 else
-    echo "*  - build sheet feature: no                                   *"
+    printf '%-64s*\n' "*  - build sheet feature: no"
 fi
 
 if [ "$HAVE_AVX512" = "1" ]; then
-    echo "*  - using 512-bit AVX instruction set                         *"
+    printf '%-64s*\n' "*  - using 512-bit AVX instruction set"
 elif [ "$CFLAGS_AVX" = "-mavx2" ]; then
-    echo "*  - using 256-bit AVX2 instruction set                        *"
+    printf '%-64s*\n' "*  - using 256-bit AVX2 instruction set"
 elif [ "$CFLAGS_AVX" = "-mavx" ]; then
-    echo "*  - using 128-bit + AVX instruction set                       *"
+    printf '%-64s*\n' "*  - using 128-bit + AVX instruction set"
 else
-    echo "*  - using 128-bit vector size, no AVX                         *"
+    printf '%-64s*\n' "*  - using 128-bit vector size, no AVX"
 fi
 
-echo "****************************************************************"
+if [ "$ZSV_NO_PARALLEL" = "1" ]; then
+    printf '%-64s*\n' "*  - CLI parallelization: DISABLED"
+else
+    printf '%-64s*\n' "*  - CLI parallelization: enabled"
+fi
+
+if [ "$USE_SIMDUTF" = "1" ]; then
+    printf '%-64s*\n' "*  - CLI check utf8: using simdutf"
+else
+    printf '%-64s*\n' "*  - CLI check utf8: not using simdutf"
+fi
+
+if [ "$ZSV_NO_ONLY_CRLF" = "1" ]; then
+    printf '%-64s*\n' "*  - only-crlf mode: DISABLED"
+else
+    printf '%-64s*\n' "*  - only-crlf mode: enabled"
+fi
+
+
+echo "*****************************************************************"
 
 if ! [ "$MAKE" = "" ]; then
     echo
